# spring config server
server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yangyun-zero/microservicecloud-config.git  # githup 上 git 仓库
          username: yangyun-zero
          password: Yyzl2840032159!
