server:
  port: 8001

mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yangyun.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: microservicecloud-dept  # 微服务名称, 如果是一个微服务组分属的多个微服务, 他们的名称相同
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://47.107.172.70:3306/cloudDB01              # 数据库名称
    username: root
    password: Root@123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
  ## 设置注册中心服务名称
    instance-id: microervicecloud-dept8001-hystrix
    ## 注册中心服务路径显示 ip
    prefer-ip-address: true

info:
  app.name: yangyun-microservicecloud
  company.name: www.yangyun.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  threadpool:
    default:
      coreSize: 10
      maximumSize: 20
      maxQueueSize: 20
      queueSizeRejectionThreshold: 10

management:
  metrics:
    hystrix:
      enabled: true



logging:
  level:
    com.yangyun.springcloud: debug