server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.10:7001/eureka,http://192.168.1.10:7002/eureka,http://192.168.1.10:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /dept/**
  ignored-services: microservicecloud-dept # 禁止使用真实服务名访问  "*" 表示禁止所有
